import Link from "next/link";
import { AppShell, Metric, ProgressSteps, Section, Status } from "@/components/prototype";

export default function PatientPage() {
  return <AppShell role="patient" active="/patient" title="Selamat pagi, Rina" description="Berikut status MCU Anda hari ini, 17 September 2026."><div className="grid gap-5 xl:grid-cols-[1.4fr_0.8fr]">
    <section className="overflow-hidden rounded-[14px] bg-[#0f766e] p-6 text-white sm:p-8"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-sm font-medium text-[#c9f1eb]">Langkah berikutnya</p><h2 className="mt-2 max-w-xl text-2xl font-bold tracking-[-0.035em] sm:text-3xl">Menuju Pemeriksaan Mata</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#dff7f3]">Ruang Poli Mata, Gedung A lantai 2. Hadir sekitar 10 menit lagi.</p></div><div className="rounded-[12px] bg-white px-5 py-4 text-center text-[#12343d]"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[#60747d]">Nomor Anda</p><p className="tabular mt-1 text-3xl font-black">A-024</p></div></div><div className="mt-8 grid grid-cols-2 gap-5 border-t border-white/20 pt-5 sm:grid-cols-4"><div><p className="text-xs text-[#c9f1eb]">Sedang dilayani</p><p className="tabular mt-1 font-bold">A-021</p></div><div><p className="text-xs text-[#c9f1eb]">Estimasi tunggu</p><p className="tabular mt-1 font-bold">12 menit</p></div><div><p className="text-xs text-[#c9f1eb]">Sisa stasiun</p><p className="tabular mt-1 font-bold">3 dari 7</p></div><div><p className="text-xs text-[#c9f1eb]">Registrasi MCU</p><p className="tabular mt-1 font-bold">MCU-260917-024</p></div></div></section>
    <Section title="Check-in digital" description="Tunjukkan kode ini kepada petugas di setiap stasiun."><div className="mx-auto grid h-36 w-36 place-items-center rounded-[12px] border border-dashed border-[#8aa2aa] bg-[#f7fafb]"><div className="grid grid-cols-3 gap-2" aria-label="Placeholder kode QR"><span className="h-7 w-7 bg-[#153945]"/><span className="h-7 w-7 bg-[#153945]"/><span className="h-7 w-7 bg-[#d8e5e8]"/><span className="h-7 w-7 bg-[#d8e5e8]"/><span className="h-7 w-7 bg-[#153945]"/><span className="h-7 w-7 bg-[#153945]"/><span className="h-7 w-7 bg-[#153945]"/><span className="h-7 w-7 bg-[#d8e5e8]"/><span className="h-7 w-7 bg-[#153945]"/></div></div><p className="mt-4 text-center text-xs text-[#60747d]">QR ilustrasi • tidak dapat dipindai</p></Section>
    <Section title="Perjalanan MCU hari ini" description="Status diperbarui setelah dikonfirmasi oleh petugas." action={<Link href="/patient/tracking" className="text-sm font-semibold text-[#087f73]">Lihat detail</Link>}><ProgressSteps items={[{label:"Registrasi & pembayaran",detail:"Selesai pukul 07.32",state:"done"},{label:"Laboratorium",detail:"Selesai pukul 08.18",state:"done"},{label:"Pemeriksaan mata",detail:"Antrean A-024 • estimasi 12 menit",state:"active"},{label:"EKG",detail:"Akan diarahkan setelah pemeriksaan mata",state:"upcoming"},{label:"Verifikasi hasil",detail:"Hasil ditinjau tenaga kesehatan",state:"upcoming"}]}/></Section>
    <div className="space-y-5"><Section title="Ringkasan kunjungan"><div className="grid grid-cols-2 gap-5"><Metric label="Paket" value="MCU Prima" detail="7 pemeriksaan"/><Metric label="Pembayaran" value="Lunas" detail="QRIS • 16 Sep"/><Metric label="Mulai" value="07.32" detail="Check-in utama"/><Metric label="Target hasil" value="Hari ini" detail="Setelah verifikasi"/></div></Section><Section title="Arah berikutnya" description="Dari Laboratorium menuju Poli Mata."><div className="soft-surface relative h-36 overflow-hidden p-4"><div className="absolute left-5 top-6 h-20 w-24 rounded-[10px] border border-[#b8c8cc] bg-white"/><div className="absolute right-5 top-10 h-16 w-28 rounded-[10px] bg-[#cceae5]"/><div className="absolute left-[42%] top-[48%] h-1 w-[25%] bg-[#087f73]"/><p className="absolute bottom-3 left-4 text-xs font-semibold text-[#4d646d]">Gedung A • lantai 2</p></div></Section></div>
    <Section title="Layanan lain" className="xl:col-span-2"><div className="grid gap-3 sm:grid-cols-3"><Link href="/patient/packages" className="soft-surface p-4"><p className="font-semibold text-[#183844]">Paket MCU</p><p className="mt-1 text-sm leading-6 text-[#60747d]">Lihat detail paket yang tersedia.</p></Link><Link href="/patient/results" className="soft-surface p-4"><p className="font-semibold text-[#183844]">Hasil & riwayat</p><p className="mt-1 text-sm leading-6 text-[#60747d]">Akses hasil yang telah diverifikasi.</p></Link><div className="soft-surface p-4"><div className="flex items-center justify-between"><p className="font-semibold text-[#183844]">Ulasan & aduan</p><Status tone="neutral">Setelah MCU</Status></div><p className="mt-1 text-sm leading-6 text-[#60747d]">Bagikan pengalaman layanan Anda.</p></div></div></Section>
  </div></AppShell>;
}
